apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: foo
  name: foobar
spec:
  template:
    spec:
      containers:
        - image: myimage:latest
          name: web
          ports:
          - containerPort: 80
          - containerPort: 443
        - image: mysql:latest
          name: db
          ports:
            - containerPort: 3306
